### ISSUE TITLE
Sem atualizações

### ISSUE THREAD

**Issue by rafaelsabino** [andeoliveira/covid19brasil#9]
Bom dia. ótimo design porém parou de atualizar em 27/04. Houve uma modificação na estrutura de dados da secretaria de saúde para englobar alguns dados SARs lá, não sei se pode ter sido isso.

**Comment by andeoliveira** [comment]
Bom dia,
Os dados estão atualizados de acordo com a API: https://brasil.io/dataset/covid19/caso/?search=&date=2020-04-29&state=PR&city=&place_type=&is_last=&city_ibge_code=&order_for_place=
Nesse exemplo filtro o estado do PR para comparação. ultima atualização 29/04.

Essas são as informações do site:
![site](https://user-images.githubusercontent.com/4259936/80805161-ad28c000-8b8d-11ea-86e2-dcf4885199e0.png)

Estou verificando se o angular não está guardando algum tipo de cache na aplicação.

Obrigado pelo comentário!

**Comment by andeoliveira** [comment]
Realizei algumas alterações no projeto na data de ontem, na versão anterior estava com a API desatualizada, se você estiver com o código em sua máquina, realiza o git pull.
Obrigado.

**Comment by rafaelsabino** [comment]
Então é este o problema. Eu tinha feito um clone local na minha máquina mesmo há qse 10 dias. Deve ser isso. Obrigado.
